api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/dotnet-core"
  id = "paketo-buildpacks/dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dotnet-core-conf"
    sha256 = "7401db4708a87429e50157ed83c5feb358ec507bb977100134ec2abe9236a915"
    source = "https://github.com/paketo-buildpacks/dotnet-core-conf/archive/v0.0.148.tar.gz"
    source_sha256 = "7e62e54db048b79567ac567b039c4a529a1d1b8332b997f9d77f82533dd8bb0c"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/dotnet-core-conf/releases/download/v0.0.148/dotnet-core-conf-0.0.148.tgz"
    version = "0.0.148"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dotnet-core-runtime"
    sha256 = "4b55d51d17b512f83acd89fc2ffbb4a7d96bb7a1423664f7522c2aaf6636004c"
    source = "https://github.com/paketo-buildpacks/dotnet-core-runtime/archive/v0.0.161.tar.gz"
    source_sha256 = "7edbc91239a34b743ed6f5a680e786e8e8bc950e0dfa103fe20e6c77aaffa859"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/dotnet-core-runtime/releases/download/v0.0.161/dotnet-core-runtime-0.0.161.tgz"
    version = "0.0.161"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dotnet-core-sdk"
    sha256 = "3f3b1bc7728d28863ec8199545ff0c815c11260ca6bd8d7d22dc3ecbbec979b1"
    source = "https://github.com/paketo-buildpacks/dotnet-core-sdk/archive/v0.0.158.tar.gz"
    source_sha256 = "10fa60da2c4f212acab7b32ca20a6fffdb332c26f7d2288cbd1fb756dbc4c05a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/dotnet-core-sdk/releases/download/v0.0.158/dotnet-core-sdk-0.0.158.tgz"
    version = "0.0.158"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/icu"
    sha256 = "16b972f3faf12ef98068c752ab17498c9de79e8a1155036debc4977cffed95b7"
    source = "https://github.com/paketo-buildpacks/icu/archive/v0.0.72.tar.gz"
    source_sha256 = "eab246058f30125c693b7a776d0a75182b56d4843ba89010d8c7d4a967317c37"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/icu/releases/download/v0.0.72/icu-0.0.72.tgz"
    version = "0.0.72"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/node-engine"
    sha256 = "ab1c7e3be23245f3550d5b9c376407dc0f53f43b846ebcb438547dd794bb48f7"
    source = "https://github.com/paketo-buildpacks/node-engine/archive/v0.0.210.tar.gz"
    source_sha256 = "8e0528307e60f36808219eba367afb235406fcb6be07c57b85dc8d94673e0d53"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/node-engine/releases/download/v0.0.210/node-engine-0.0.210.tgz"
    version = "0.0.210"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dotnet-core-aspnet"
    sha256 = "a00147d6c556e98780ad12839a0a308b8f7f8a3c2fc35ac110b4b0dd7278f963"
    source = "https://github.com/paketo-buildpacks/dotnet-core-aspnet/archive/v0.0.157.tar.gz"
    source_sha256 = "562eae30174bf6c3b1c3e914f2469d2da3ba48aeba9c58f69c7b695b1362e71d"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/dotnet-core-aspnet/releases/download/v0.0.157/dotnet-core-aspnet-0.0.157.tgz"
    version = "0.0.157"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dotnet-core-build"
    sha256 = "985bffc6cc666b0b736186bf78200ce5c3fd55813d45d929dc5ee9eee81eb8db"
    source = "https://github.com/paketo-buildpacks/dotnet-core-build/archive/v0.0.92.tar.gz"
    source_sha256 = "ee45ace4b871815efcdf0573128d7d8c1d378ce8961aab2b3bffaadc0ff4fec6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/dotnet-core-build/releases/download/v0.0.92/dotnet-core-build-0.0.92.tgz"
    version = "0.0.92"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.210"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/icu"
    version = "0.0.72"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core-runtime"
    version = "0.0.161"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core-aspnet"
    version = "0.0.157"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core-sdk"
    version = "0.0.158"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core-build"
    version = "0.0.92"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core-conf"
    version = "0.0.148"
