api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/dotnet-core"
  id = "paketo-buildpacks/dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dotnet-core-conf"
    sha256 = "cb2d8d5dd3a541c7aa6a26216797a497b3169c9924a8cc890b20c9be2ea75745"
    source = "https://github.com/paketo-buildpacks/dotnet-core-conf/archive/v0.0.152.tar.gz"
    source_sha256 = "7f4fcdd825aa2adfe4b6e2c12f452e09562b44055a118409cb1e1dde973ef75e"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/dotnet-core-conf/releases/download/v0.0.152/dotnet-core-conf-0.0.152.tgz"
    version = "0.0.152"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dotnet-core-runtime"
    sha256 = "7b2fc51d3411d627721579361180317552c0071a6b4ef94a929c07e3c9358a26"
    source = "https://github.com/paketo-buildpacks/dotnet-core-runtime/archive/v0.0.166.tar.gz"
    source_sha256 = "fa0a4ea3f2bd85548f292d8c36c7dc86ef2301a98421701f3fdfcdd208623b1b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/dotnet-core-runtime/releases/download/v0.0.166/dotnet-core-runtime-0.0.166.tgz"
    version = "0.0.166"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dotnet-core-sdk"
    sha256 = "eafeed425c3663906312064cbc64eb178da1583723ce65a33fa8d7589b0bf44b"
    source = "https://github.com/paketo-buildpacks/dotnet-core-sdk/archive/v0.0.164.tar.gz"
    source_sha256 = "0a9dda837509952606f62671950be374d333bb793449357166c967df33158297"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/dotnet-core-sdk/releases/download/v0.0.164/dotnet-core-sdk-0.0.164.tgz"
    version = "0.0.164"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/icu"
    sha256 = "66c5e43d4220fca14582f50c45fae2826b27b031d7187b13c65213618fd1b385"
    source = "https://github.com/paketo-buildpacks/icu/archive/v0.0.75.tar.gz"
    source_sha256 = "eb1ed84997c362c543493eab380189c824614a95841f057d9fe2a2afe90cf651"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/icu/releases/download/v0.0.75/icu-0.0.75.tgz"
    version = "0.0.75"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/node-engine"
    sha256 = "0b18b76eae7d9609b04220854f04350db8063536ac35eab9165b5f53137c613a"
    source = "https://github.com/paketo-buildpacks/node-engine/archive/v0.0.220.tar.gz"
    source_sha256 = "bebe9ee706bef48653410b188d7905ac5241292d9ae958926cd4a254d022f329"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/node-engine/releases/download/v0.0.220/node-engine-0.0.220.tgz"
    version = "0.0.220"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dotnet-core-aspnet"
    sha256 = "b020e52ccea85234d8dc4f1292f6fd4acddfcbce4e680eda1f04bee0ab5b0e2a"
    source = "https://github.com/paketo-buildpacks/dotnet-core-aspnet/archive/v0.0.163.tar.gz"
    source_sha256 = "96c0df9de9dbfb0f4955c4ce7cbfa94bf9afbc6d54277b72f574eeac5a0d618d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/dotnet-core-aspnet/releases/download/v0.0.163/dotnet-core-aspnet-0.0.163.tgz"
    version = "0.0.163"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dotnet-core-build"
    sha256 = "e76a2c557549201d551b542d94a5b894a2cc8595b294f8b597b829a17321a4d1"
    source = "https://github.com/paketo-buildpacks/dotnet-core-build/archive/v0.0.95.tar.gz"
    source_sha256 = "02c34dc6e6c0252af5c4050033c4f4280b48229569f69ef51e6b63d589869e9b"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/dotnet-core-build/releases/download/v0.0.95/dotnet-core-build-0.0.95.tgz"
    version = "0.0.95"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.220"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/icu"
    version = "0.0.75"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core-runtime"
    version = "0.0.166"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core-aspnet"
    version = "0.0.163"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core-sdk"
    version = "0.0.164"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core-build"
    version = "0.0.95"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core-conf"
    version = "0.0.152"
