api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/dotnet-core"
  id = "paketo-buildpacks/dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dotnet-core-conf"
    sha256 = "8d3fe5b97aaaadfcf2cf871fcc28aa4d77318e0ceafee2bfd98da7bc79192caf"
    source = "https://github.com/paketo-buildpacks/dotnet-core-conf/archive/v0.0.158.tar.gz"
    source_sha256 = "b9bf61e44fca47bc039caaf93da7211c0fe5bef469b166dcb03ffbbcb9d791db"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/dotnet-core-conf/releases/download/v0.0.158/dotnet-core-conf-0.0.158.tgz"
    version = "0.0.158"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dotnet-core-runtime"
    sha256 = "38198ab30c2e29aff19b0f6b57c1f19a6a8eb0e5098ff240af92dc5dd3488a55"
    source = "https://github.com/paketo-buildpacks/dotnet-core-runtime/archive/v0.0.172.tar.gz"
    source_sha256 = "9078de0e2803ec17f9ce1f02ce8848d6588d91d7b4d22a86286d33103678977b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/dotnet-core-runtime/releases/download/v0.0.172/dotnet-core-runtime-0.0.172.tgz"
    version = "0.0.172"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dotnet-core-sdk"
    sha256 = "b6ade13569c5344910e43684e0c4e6477b6818d98c3ace1e9eb0e43181458bd2"
    source = "https://github.com/paketo-buildpacks/dotnet-core-sdk/archive/v0.0.172.tar.gz"
    source_sha256 = "9ae15cadeef74663cf3b9d9a932436413c3e561bc51a2dd515f2e88358d29474"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/dotnet-core-sdk/releases/download/v0.0.172/dotnet-core-sdk-0.0.172.tgz"
    version = "0.0.172"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/icu"
    sha256 = "693d2ce4e16f142e0bc9c9370be5f5c1ca01d76ac62ae91ccc48b35486476d25"
    source = "https://github.com/paketo-buildpacks/icu/archive/v0.0.80.tar.gz"
    source_sha256 = "1c0d92e14c40f7769f971e2909ba1ae0b68e56888d8746a9a664055f95797c91"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/icu/releases/download/v0.0.80/icu-0.0.80.tgz"
    version = "0.0.80"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/node-engine"
    sha256 = "497d6e4c50f429d8d3acd0e644e0143204c3143a7c8822fc9b492ab32bb0d737"
    source = "https://github.com/paketo-buildpacks/node-engine/archive/v0.0.234.tar.gz"
    source_sha256 = "0e8e363dc40ae1055690fdfe2eff0d22fa7d6486f9bfa6d1dac9914ac34f2ef6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/node-engine/releases/download/v0.0.234/node-engine-0.0.234.tgz"
    version = "0.0.234"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dotnet-core-aspnet"
    sha256 = "5fb06b83a01f6ed8b5caf5a45847c3a7727c90849c6801d2df42fb5ac0392cdb"
    source = "https://github.com/paketo-buildpacks/dotnet-core-aspnet/archive/v0.0.168.tar.gz"
    source_sha256 = "df16fe29e7a979d348109490664ad4831395620fe29b0f73aa4db023b3ee315e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://github.com/paketo-buildpacks/dotnet-core-aspnet/releases/download/v0.0.168/dotnet-core-aspnet-0.0.168.tgz"
    version = "0.0.168"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/dotnet-core-build"
    sha256 = "7df4917c9e7a2cfd1078291d274c56f2d3256f604c6408e9ebb0c03b0e4bf2bd"
    source = "https://github.com/paketo-buildpacks/dotnet-core-build/archive/v0.0.101.tar.gz"
    source_sha256 = "12bf95edeb6f86f597df12d7955e7100fef3875702b943723031704ff5e68e38"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3", "io.buildpacks.stacks.bionic"]
    uri = "https://github.com/paketo-buildpacks/dotnet-core-build/releases/download/v0.0.101/dotnet-core-build-0.0.101.tgz"
    version = "0.0.101"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.234"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/icu"
    version = "0.0.80"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core-runtime"
    version = "0.0.172"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core-aspnet"
    version = "0.0.168"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core-sdk"
    version = "0.0.172"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core-build"
    version = "0.0.101"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core-conf"
    version = "0.0.158"
